sudo: required

language: generic

services:
  - docker

before_install:
  - docker-compose up -d --build
  - docker-compose ps
  - docker ps -a

script:
  - docker-compose exec truffle yarn run test:ci

after_success:
  - bash <(curl -s https://scripts.scantist.com/ci-travis.sh)
